name: Build & Release Signed Ionic Android App (APK Format)

on:
  workflow_call:
    secrets:
      ANDROID_KEYSTORE_BASE64:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true
      KEY_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download www artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./www

      - name: Extract web artifact
        run: |
          tar -xf ./www/artifact.tar -C ./www
          rm ./www/artifact.tar

      - name: Install Node.js dependencies
        run: npm ci

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Copy www assets to Android
        run: npx cap copy android

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          VERSION_CODE=$(echo $VERSION | awk -F. '{print $1*10000 + $2*100 + $3}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "Version: $VERSION, VersionCode: $VERSION_CODE"

      - name: Set version in build.gradle
        run: |
          source $GITHUB_ENV
          sed -i "s/versionName \".*\"/versionName \"${VERSION}\"/" android/app/build.gradle
          sed -i "s/versionCode [0-9]\+/versionCode ${VERSION_CODE}/" android/app/build.gradle

      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      - name: Build signed Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd android
          KEYSTORE_PATH="$(pwd)/app/my-release-key.jks"
          echo "Using keystore at $KEYSTORE_PATH"
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
          cd ..

      - name: Rename build outputs
        run: |
          source $GITHUB_ENV
          mv android/app/build/outputs/apk/release/app-release-signed.apk ./PflanzenABC-v${VERSION}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release v${{ env.VERSION }}"
          body: |
            🚀 **Automatically created release for version v${{ env.VERSION }}**

            **VersionCode:** ${{ env.VERSION_CODE }}
            **Buildsystem:** Ionic + Capacitor + Gradle
          files: |
            ./PflanzenABC-v${VERSION}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
