name: Build Ionic App

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Ionic app
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync

      - name: Fix file permissions for GitHub Pages
        run: |
          find www -type d -exec chmod 755 {} \;
          find www -type f -exec chmod 644 {} \;

      - name: Upload built web assets
        uses: actions/upload-pages-artifact@v3
        with:
          path: www
