name: Main CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deps:
    uses: ./.github/workflows/build.yml

  web:
    needs: build-deps
    uses: ./.github/workflows/web.yml

  android-debug:
    if: startsWith(github.ref, 'refs/heads/')
    needs: build-deps
    uses: ./.github/workflows/android-debug.yml
    secrets: inherit

  android-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-deps
    uses: ./.github/workflows/android-release.yml
    secrets: inherit
