name: Deploy Web to GitHub Pages

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download built www/ from previous job
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./www

      - name: Deploy www/ to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./www

